name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - jupyter
      - jinja2<3.1.0
      - seaborn==0.11.1
      - pandas-profiling==3.6.6
      - streamlit==0.62.0
      - fastparquet
